import React from 'react';

export default function BdDistrict() {
    return [
        { label: 'Bagerhat', value: 'Bagerhat' },
        { label: 'Bandarban', value: 'Bandarban' },
        { label: 'Barguna', value: 'Barguna' },
        { label: 'Barisal', value: 'Barisal' },
        { label: 'Bhola', value: 'Bhola' },
        { label: 'Bogra', value: 'Bogra' },
        { label: 'Brahmanbaria', value: 'Brahmanbaria' },
        { label: 'Chandpur', value: 'Chandpur' },
        { label: 'Chittagong', value: 'Chittagong' },
        { label: 'Chuadanga', value: 'Chuadanga' },
        { label: 'Comilla', value: 'Comilla' },
        { label: "Cox's Bazar", value: "Cox's Bazar" },
        { label: 'Dhaka', value: 'Dhaka' },
        { label: 'Dinajpur', value: 'Dinajpur' },
        { label: 'Faridpur', value: 'Faridpur' },
        { label: 'Feni', value: 'Feni' },
        { label: 'Gaibandha', value: 'Gaibandha' },
        { label: 'Gazipur', value: 'Gazipur' },
        { label: 'Gopalganj', value: 'Gopalganj' },
        { label: 'Habiganj', value: 'Habiganj' },
        { label: 'Jaipurhat', value: 'Jaipurhat' },
        { label: 'Jamalpur', value: 'Jamalpur' },
        { label: 'Jessore', value: 'Jessore' },
        { label: 'Jhalokati', value: 'Jhalokati' },
        { label: 'Jhenaidah', value: 'Jhenaidah' },
        { label: 'Khagrachari', value: 'Khagrachari' },
        { label: 'Khulna', value: 'Khulna' },
        { label: 'Kishoreganj', value: 'Kishoreganj' },
        { label: 'Kurigram', value: 'Kurigram' },
        { label: 'Kushtia', value: 'Kushtia' },
        { label: 'Lakshmipur', value: 'Lakshmipur' },
        { label: 'Lalmonirhat', value: 'Lalmonirhat' },
        { label: 'Madaripur', value: 'Madaripur' },
        { label: 'Magura', value: 'Magura' },
        { label: 'Manikganj', value: 'Manikganj' },
        { label: 'Maulvibazar', value: 'Maulvibazar' },
        { label: 'Meherpur', value: 'Meherpur' },
        { label: 'Munshiganj', value: 'Munshiganj' },
        { label: 'Mymensingh', value: 'Mymensingh' },
        { label: 'Naogaon', value: 'Naogaon' },
        { label: 'Narail', value: 'Narail' },
        { label: 'Narayanganj', value: 'Narayanganj' },
        { label: 'Narsingdi', value: 'Narsingdi' },
        { label: 'Natore', value: 'Natore' },
        { label: 'Nawabganj', value: 'Nawabganj' },
        { label: 'Netrokona', value: 'Netrokona' },
        { label: 'Nilphamari', value: 'Nilphamari' },
        { label: 'Noakhali', value: 'Noakhali' },
        { label: 'Pabna', value: 'Pabna' },
        { label: 'Panchagarh', value: 'Panchagarh' },
        { label: 'Patuakhali', value: 'Patuakhali' },
        { label: 'Pirojpur', value: 'Pirojpur' },
        { label: 'Rajbari', value: 'Rajbari' },
        { label: 'Rajshahi', value: 'Rajshahi' },
        { label: 'Rangamati', value: 'Rangamati' },
        { label: 'Rangpur', value: 'Rangpur' },
        { label: 'Satkhira', value: 'Satkhira' },
        { label: 'Shariatpur', value: 'Shariatpur' },
        { label: 'Sherpur', value: 'Sherpur' },
        { label: 'Sirajganj', value: 'Sirajganj' },
        { label: 'Sunamganj', value: 'Sunamganj' },
        { label: 'Sylhet', value: 'Sylhet' },
        { label: 'Tangail', value: 'Tangail' },
        { label: 'Thakurgaon', value: 'Thakurgaon' }
    ];
}
